version: "3.0"

services:
    beacon_node:
        image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
        volumes:
            - ${LIGHTHOUSE_DATADIR:-./data/lighthouse-data}:/root/.lighthouse
            - ./scripts:/root/scripts:ro
            - ./data:/root/jwttoken
        ports:
            - 5052:5052/tcp
            - 5053:5053/tcp
            - 5054:5054/tcp     # metrics endpoint
            - 9000:9000/tcp
            - 9000:9000/udp
        env_file: .env
        command: sh /root/scripts/start-beacon-node.sh
        # restart: on-failure
    validator_client:
        image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
        volumes:
            - ./data/lighthouse-data:/root/.lighthouse
            - ./scripts:/root/scripts:ro
            - ./data/validator_keys:/root/validator_keys
        depends_on:
            - beacon_node
        ports:
            - 5064:5064/tcp     # metrics endpoint
        env_file: .env
        command: sh /root/scripts/start-validator-client.sh
        # restart: on-failure
    geth:
        image: ethereum/client-go:${GETH_VERSION}
        volumes:
            - ${GETH_DATADIR:-./data/geth-data}:/root/.ethereum
            - ./data:/root/jwttoken
        ports:
            - 30303:30303/tcp
            - 30303:30303/udp
            - 8545:8545
            - 8546:8546
        env_file: .env
        command:
            - --http
            - --http.api=eth,net,engine,admin,web3
            - --http.addr=0.0.0.0
            - --http.vhosts=*
            - --http.corsdomain=*
            - --ws
            - --ws.origins=*
            - --ws.addr=0.0.0.0
            - --ws.api=eth,net,web3
            - --syncmode=full
            - --authrpc.addr=0.0.0.0
            - --authrpc.port=8551
            - --authrpc.vhosts=*
            - --authrpc.jwtsecret=/root/jwttoken/jwt.hex
        restart: on-failure
        logging:
            driver: json-file
            options:
              max-size: "50m"
              max-file: "10"